name: Deploy to Self-Hosted Runner

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Show the user
      run: |
        whoami

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Deploy to self-hosted runner
      run: |
        docker stop my-app || true
        docker rm my-app || true
        docker run -d --name my-app -p 3000:3000 my-app:latest
